### ISSUE TITLE
Replicate backend is able to receive my request, but my page remains in a waiting state

### ISSUE THREAD

**Issue by 973398769** [cbh123/stickerbaker#11]
Hi @cbh123 Many thanks for you help! I observed that the replicate backend is able to receive my request, but the generated image does not return to my page. My page remains in a waiting state. I would like to ask where the problem might be? Thank you for your assistance. I really appreciate it. 
<img width="1421" alt="Screenshot 2024-03-15 at 5 07 22 PM" src="https://github.com/cbh123/stickerbaker/assets/50310195/3d5de311-27e0-4c90-bc69-7c79df13b15d">

**Comment by cbh123** [comment]
Make sure you set up the webhook! Info should be in the readme
