### ISSUE TITLE
missing DATABASE_URL when launch to fly.io

### ISSUE THREAD

**Issue by mink365** [cbh123/stickerbaker#3]
ERROR! Config provider Config.Reader failed with:
  ** (RuntimeError) environment variable DATABASE_URL is missing.
  For example: ecto://USER:PASS@HOST/DATABASE
      /app/releases/0.1.0/runtime.exs:41: (file)
      (elixir 1.16.0) src/elixir.erl:405: :elixir.eval_external_handler/3
      (stdlib 5.2) erl_eval.erl:750: :erl_eval.do_apply/7
      (stdlib 5.2) erl_eval.erl:494: :erl_eval.expr/6
      (stdlib 5.2) erl_eval.erl:136: :erl_eval.exprs/6

so, where to find the DATABASE_URL for my project?
thinks

**Comment by cbh123** [comment]
Make sure when you `fly launch` you set up a Postgres DB!
