### ISSUE TITLE
Raising Error  (KeyError) key :prompt not found in: nil

### ISSUE THREAD

**Issue by hassanRsiddiqi** [cbh123/stickerbaker#5]
** (KeyError) key :prompt not found in: nil
If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
(sticker 0.1.0) lib/sticker/embeddings/worker.ex:44: Sticker.Embeddings.Worker.create_text_embedding/1
(sticker 0.1.0) lib/sticker/embeddings/worker.ex:79: Sticker.Embeddings.Worker.handle_info/2
(stdlib 5.2) gen_server.erl:1095: :gen_server.try_handle_info/3
(stdlib 5.2) gen_server.erl:1183: :gen_server.handle_msg/6
(stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: :work

**Comment by hassanRsiddiqi** [comment]
This happended on fresh DB.

**Comment by cbh123** [comment]
Ah, that's because it's trying to create embeddings (used for search, WIP) on an empty DB. You can comment out these two lines in application.ex to fix it for now:

      {Sticker.Embeddings.Index, []},
      Sticker.Embeddings.Worker
